<?xml version="1.0"?>
<package format="3">
  <name>cover_wyh</name>
  <version>0.0.1</version>
  <description>Rectangle coverage planner with RViz visualization for ROS 2.</description>

  <maintainer email="wyh@example.com">wyh</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>geometry_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>rclcpp</depend>
  <depend>std_msgs</depend>
  <depend>visualization_msgs</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
